#!/usr/bin/env bash

pandoc $currfile -s --to=html5 -o $pandoc/$1.html \
            --mathjax \
            --highlight-style=tango \
            --lua-filter=$pandoc/assets/link2html.lua \
            -H $pandoc/assets/header.html \
            -T $prefixtail
